
  protected


    function Get_Author:String;
    function Get_AuthorQQ:String;
    function Get_AuthorEmail:String;
    function Get_AuthorMobile:String;

    function Get_Version:String;


published
    property _Author:String read Get_Author;
    property _AuthorQQ:String read Get_AuthorQQ;
    property _AuthorEmail:String read Get_AuthorEmail;
    property _AuthorMobile:String read Get_AuthorMobile;

    property _Version:String read Get_Version;

