

  function GetLeft:TControlSize;
  function GetTop:TControlSize;
  procedure SetLeft(const Value:TControlSize);
  procedure SetTop(const Value:TControlSize);
  function GetWidth:TControlSize;
  function GetHeight:TControlSize;
  procedure SetWidth(const Value:TControlSize);
  procedure SetHeight(const Value:TControlSize);


  procedure SetParent(const Value:TParentControl);
  procedure SetVisible(const Value:Boolean);



  function GetWidthInt:Integer;
  procedure SetWidthInt(const Value:Integer);
  function GetHeightInt:Integer;
  procedure SetHeightInt(const Value:Integer);



  function GetIsMouseOver:Boolean;
  procedure SetIsMouseOver(const Value:Boolean);
  function GetIsMouseDown:Boolean;
  procedure SetIsMouseDown(const Value:Boolean);



  function GetVisible:Boolean;
  function GetEnabled:Boolean;
  function GetFocused:Boolean;
  procedure SetFocused(const Value:Boolean);
  function GetParent:TParentControl;


