

function {$I Source\Controls\ISkinComponent_Skin_Impl_ClassName.inc}.Get_Author: String;
begin
  Result:=OrangeUIControl_Author;
end;

function {$I Source\Controls\ISkinComponent_Skin_Impl_ClassName.inc}.Get_AuthorQQ: String;
begin
  Result:=OrangeUIControl_AuthorQQ;
end;

function {$I Source\Controls\ISkinComponent_Skin_Impl_ClassName.inc}.Get_AuthorEmail: String;
begin
  Result:=OrangeUIControl_AuthorEmail;
end;

function {$I Source\Controls\ISkinComponent_Skin_Impl_ClassName.inc}.Get_AuthorMobile: String;
begin
  Result:=OrangeUIControl_AuthorMobile;
end;

function {$I Source\Controls\ISkinComponent_Skin_Impl_ClassName.inc}.Get_Version: String;
begin
  Result:=OrangeUIControl_Version;
end;


