



//procedure {$I Source\Controls\INC\Common\ISkinControl_Control_Impl_ClassName.inc}.SetIsMouseDown(const Value: Boolean);
//begin
//    Self.FIsMouseDown:=Value;
//end;
//
//procedure {$I Source\Controls\INC\Common\ISkinControl_Control_Impl_ClassName.inc}.SetIsMouseOver(const Value: Boolean);
//begin
//    Self.FIsMouseOver:=Value;
//end;
//
//function {$I Source\Controls\INC\Common\ISkinControl_Control_Impl_ClassName.inc}.GetIsMouseDown: Boolean;
//begin
//  Result:=FIsMouseDown;
//end;
//
//function {$I Source\Controls\INC\Common\ISkinControl_Control_Impl_ClassName.inc}.GetIsMouseOver: Boolean;
//begin
//  Result:=FIsMouseOver;
//end;

